### PR TITLE
Works with Python 3.x (trying this again)

### PR DESCRIPTION
**Pull request by griffin2000**
I have upgraded the code to work with Python 3.x. I have not tested exhaustively but verified (with Python 3.5.1) that I can inject video metadata and YouTube will understand it (and read it back with the spatialaudio app). I've not tested the audio side. My last PR had a error in the byte-string conversion code, fixed in this version.

### CODE REVIEW

**Comment by griffin2000** [comment]
I have a CLA (signed Dec 06, 2016 13:18 PST)

**Comment by griffin2000** [comment]
All these commits are from me (Gareth Morgan, username: griffin2000)

**Comment by griffin2000** [comment]
Any idea what the issue is with this? I have CLA for all the account involved in this, but the PR still failed. It's pretty irritating having to use this fork and keep it up to date with the main one. @dcower, anyone?

**Comment by mqarty** [comment]
Can we get this resolved?

**Comment by jamiesonpepper** [comment]
@mqarty The current master branch is compatible with Python 3.10 and I assume later. I haven't had a chance to release new binaries yet for Mac/Windows. Closing this pull request out.

**Pull request closed without merging**
